# Generated by Django 4.2.7 on 2024-02-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymsession', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymsession',
            old_name='person',
            new_name='user',
        ),
    ]
