# Generated by Django 4.2.7 on 2024-02-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_gymsession', '0002_rename_person_gymsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsession',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
