# Generated by Django 4.2.7 on 2024-02-03 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_gymsession', '0003_alter_gymsession_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymsession',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='gymsession',
            unique_together={('user', 'day')},
        ),
    ]
